#!/usr/bin/env bash
# =============================================================
# AERO-SEA SENTINEL — Master Setup Script
# Usage: bash scripts/setup.sh [--dev | --prod | --reset]
# =============================================================
set -euo pipefail
IFS=$'\n\t'

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

MODE="${1:---dev}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

banner() {
  echo -e "${CYAN}"
  cat << 'EOF'
  ╔══════════════════════════════════════════════════════╗
  ║                                                      ║
  ║        🛸  AERO-SEA SENTINEL PLATFORM                ║
  ║        Complete Setup & Launch                       ║
  ║                                                      ║
  ╚══════════════════════════════════════════════════════╝
EOF
  echo -e "${RESET}"
}

step() { echo -e "${BOLD}${GREEN}▶ $1${RESET}"; }
warn() { echo -e "${YELLOW}⚠  $1${RESET}"; }
err()  { echo -e "${RED}✗  $1${RESET}"; exit 1; }
ok()   { echo -e "${GREEN}✓  $1${RESET}"; }

# ── Checks ───────────────────────────────────────────────────
check_deps() {
  step "Checking dependencies..."
  local missing=()
  for cmd in docker docker-compose node npm python3 pip3 curl; do
    if ! command -v "$cmd" &>/dev/null; then
      missing+=("$cmd")
    fi
  done
  if [ ${#missing[@]} -gt 0 ]; then
    warn "Missing: ${missing[*]}"
    warn "Install Docker Desktop from https://docker.com and Node.js from https://nodejs.org"
  fi
  ok "Dependency check done"
}

# ── Environment ───────────────────────────────────────────────
setup_env() {
  step "Setting up environment files..."
  cd "$ROOT_DIR"

  if [ ! -f .env ]; then
    JWT_SECRET=$(LC_ALL=C tr -dc 'A-Za-z0-9!@#$%^&*' </dev/urandom | head -c 64 || echo "sentinel_jwt_secret_placeholder_$(date +%s)")
    DB_PASS=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24 || echo "sentinel_db_pass_$(date +%s)")

    cat > .env << EOF
# Auto-generated by setup.sh $(date)
DB_PASSWORD=${DB_PASS}
JWT_SECRET=${JWT_SECRET}
GRAFANA_PASSWORD=sentinel_grafana
OLLAMA_MODEL=llama3:8b
CORS_ORIGINS=http://localhost,http://localhost:3000
VITE_API_URL=/api/v1
VITE_WS_URL=ws://localhost/ws/telemetry
EOF
    ok "Created .env with secure secrets"
  else
    ok ".env already exists — skipping"
  fi

  if [ ! -f backend/.env ]; then
    cp backend/.env.example backend/.env
    # Merge root .env values
    source .env
    sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${DB_PASSWORD}/" backend/.env
    sed -i "s/JWT_SECRET=.*/JWT_SECRET=${JWT_SECRET}/" backend/.env
    ok "Created backend/.env"
  fi
}

# ── Docker build & up ─────────────────────────────────────────
docker_up() {
  step "Building and starting Docker services..."
  cd "$ROOT_DIR"

  if [ "$MODE" = "--reset" ]; then
    warn "Resetting all volumes..."
    docker-compose down -v --remove-orphans 2>/dev/null || true
  fi

  docker-compose build --parallel
  docker-compose up -d

  ok "All services started"
}

# ── Wait for services ─────────────────────────────────────────
wait_for() {
  local name="$1" url="$2" retries="${3:-30}"
  printf "  Waiting for ${name}"
  for i in $(seq 1 $retries); do
    if curl -fs "$url" &>/dev/null; then
      echo -e " ${GREEN}✓${RESET}"
      return 0
    fi
    printf "."
    sleep 2
  done
  echo -e " ${YELLOW}(timeout — may still be starting)${RESET}"
  return 0
}

wait_services() {
  step "Waiting for services to be healthy..."
  wait_for "PostgreSQL"  "http://localhost:4000/health" 40
  wait_for "Backend API" "http://localhost:4000/health" 20
  wait_for "AI Service"  "http://localhost:8000/health" 30
  wait_for "Frontend"    "http://localhost:3000"        20
  wait_for "Grafana"     "http://localhost:3001"        20
}

# ── Pull Ollama model ─────────────────────────────────────────
pull_model() {
  step "Pulling Llama 3 8B model (this may take a few minutes the first time)..."
  if docker exec sentinel-ollama ollama list 2>/dev/null | grep -q "llama3"; then
    ok "Llama 3 model already present"
  else
    warn "Pulling llama3:8b (~4.7GB) — please wait..."
    docker exec sentinel-ollama ollama pull llama3:8b || warn "Model pull failed — AI features may be limited"
    ok "Model ready"
  fi
}

# ── Dev mode — npm install ────────────────────────────────────
dev_install() {
  if [ "$MODE" = "--dev" ]; then
    step "Installing local dev dependencies..."
    cd "$ROOT_DIR/backend"  && npm install 2>/dev/null && ok "Backend deps installed"
    cd "$ROOT_DIR/frontend" && npm install 2>/dev/null && ok "Frontend deps installed"
    cd "$ROOT_DIR/simulator" && npm install 2>/dev/null && ok "Simulator deps installed"
    cd "$ROOT_DIR/ai-service" && pip3 install -q -r requirements.txt && ok "Python deps installed"
  fi
}

# ── Print access URLs ─────────────────────────────────────────
print_urls() {
  echo ""
  echo -e "${CYAN}╔═══════════════════════════════════════════════╗${RESET}"
  echo -e "${CYAN}║  🚀  SENTINEL PLATFORM IS RUNNING             ║${RESET}"
  echo -e "${CYAN}╠═══════════════════════════════════════════════╣${RESET}"
  echo -e "${CYAN}║${RESET}  Frontend          http://localhost           ${CYAN}║${RESET}"
  echo -e "${CYAN}║${RESET}  Frontend (direct) http://localhost:3000      ${CYAN}║${RESET}"
  echo -e "${CYAN}║${RESET}  REST API          http://localhost:4000/api  ${CYAN}║${RESET}"
  echo -e "${CYAN}║${RESET}  AI Service        http://localhost:8000      ${CYAN}║${RESET}"
  echo -e "${CYAN}║${RESET}  Grafana           http://localhost:3001      ${CYAN}║${RESET}"
  echo -e "${CYAN}║${RESET}  Prometheus        http://localhost:9090      ${CYAN}║${RESET}"
  echo -e "${CYAN}╠═══════════════════════════════════════════════╣${RESET}"
  echo -e "${CYAN}║  Demo Credentials:                            ║${RESET}"
  echo -e "${CYAN}║${RESET}  admin@sentinel.io    → ADMIN                 ${CYAN}║${RESET}"
  echo -e "${CYAN}║${RESET}  fleet@sentinel.io    → FLEET MANAGER         ${CYAN}║${RESET}"
  echo -e "${CYAN}║${RESET}  analyst@sentinel.io  → ANALYST               ${CYAN}║${RESET}"
  echo -e "${CYAN}║${RESET}  senior@sentinel.io   → SENIOR OPERATOR       ${CYAN}║${RESET}"
  echo -e "${CYAN}║${RESET}  operator@sentinel.io → OPERATOR              ${CYAN}║${RESET}"
  echo -e "${CYAN}║${RESET}  Password: Sentinel2025!                      ${CYAN}║${RESET}"
  echo -e "${CYAN}╚═══════════════════════════════════════════════╝${RESET}"
  echo ""
  echo -e "  View logs:  ${BOLD}docker-compose logs -f${RESET}"
  echo -e "  Stop all:   ${BOLD}docker-compose down${RESET}"
  echo -e "  Reset:      ${BOLD}bash scripts/setup.sh --reset${RESET}"
  echo ""
}

# ── Main ──────────────────────────────────────────────────────
banner
check_deps
setup_env
dev_install
docker_up
wait_services
pull_model
print_urls
